---
- hosts: web1
  become: true

  tasks:
          - name: Create apache container 
            docker_container:
                    name: "apache"
                    image: "httpd"
                    state: started
                    exposed_ports:
                            - "80"
                    ports:
                            - "80:80"
                    volumes:
                            - /home/vagrant/website-apache:/usr/local/apache2/htdocs/
                            
          - name: Create nginx container
            docker_container:
                    name: "mynginx"
                    image: "nginx"
                    state: started
                    exposed_ports:
                            - "80"
                    ports:
                            - "8080:80"
                    volumes:
                            - /home/vagrant/website-nginx:/usr/share/nginx/html/
