---
- hosts: web1
  become: true

  tasks:
          - name: Stop and disable Docker
            ansible.builtin.systemd:
                    name: docker
                    enabled: no
                    state: stopped

