---
- hosts: web1
  become: true

  tasks:
          - name: Start and enable Docker service
            ansible.builtin.systemd:
                    name: docker
                    enabled: yes
                    state: started
